language: csharp
os:
  - linux

# Ubuntu 14.04
sudo: required
dist: trusty

mono:
  - latest
dotnet: 2.1.400

if: tag IS blank

script:
  - ./build.sh --target Travis

cache:
  directories:
    - src/packages
    - tools/Addins
    - tools/Cake
